// Code generated by golex. DO NOT EDIT.

// blame: jnml, labs.nic.cz
package main

import (
	"bufio"
	"log"
	//"fmt"
	//"strconv"
)

type yylexer struct {
	src     *bufio.Reader
	buf     []byte
	empty   bool
	current byte
}

func newLexer(src *bufio.Reader) (y *yylexer) {
	y = &yylexer{src: src}
	if b, err := src.ReadByte(); err == nil {
		y.current = b
	}
	return
}

func (y *yylexer) getc() byte {
	if y.current != 0 {
		y.buf = append(y.buf, y.current)
	}
	y.current = 0
	if b, err := y.src.ReadByte(); err == nil {
		y.current = b
	}
	return y.current
}

func (y yylexer) Error(e string) {
	log.Fatal(e)
}

func (y *yylexer) Lex(lval *yySymType) int {
	c := y.current
	if y.empty {
		c, y.empty = y.getc(), false
	}

yystate0:

	y.buf = y.buf[:0]

	goto yystart1

	goto yystate0 // silence unused label error
	goto yystate1 // silence unused label error
yystate1:
	c = y.getc()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate3
	case c == '#':
		goto yystate5
	case c == '-':
		goto yystate7
	case c == '/':
		goto yystate9
	case c == 'A' || c == 'a':
		goto yystate41
	case c == 'B' || c == 'b':
		goto yystate44
	case c == 'C' || c == 'c':
		goto yystate46
	case c == 'D' || c == 'd':
		goto yystate63
	case c == 'E' || c == 'e':
		goto yystate71
	case c == 'F' || c == 'f':
		goto yystate78
	case c == 'G' || c == 'g':
		goto yystate97
	case c == 'H' || c == 'J' || c == 'O' || c == 'Q' || c == 'V' || c >= 'X' && c <= 'Z' || c == '_' || c == 'h' || c == 'j' || c == 'o' || c == 'q' || c == 'v' || c >= 'x' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	case c == 'I' || c == 'i':
		goto yystate100
	case c == 'K' || c == 'k':
		goto yystate103
	case c == 'L' || c == 'l':
		goto yystate104
	case c == 'M' || c == 'm':
		goto yystate112
	case c == 'N' || c == 'n':
		goto yystate135
	case c == 'P' || c == 'p':
		goto yystate139
	case c == 'R' || c == 'r':
		goto yystate149
	case c == 'S' || c == 's':
		goto yystate165
	case c == 'T' || c == 't':
		goto yystate169
	case c == 'U' || c == 'u':
		goto yystate176
	case c == 'W' || c == 'w':
		goto yystate189
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	case c >= '0' && c <= '9':
		goto yystate27
	}

yystate2:
	c = y.getc()
	switch {
	default:
		goto yyrule4
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate4
	case c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '!' || c >= '#' && c <= 'ÿ':
		goto yystate3
	}

yystate4:
	c = y.getc()
	goto yyrule67

yystate5:
	c = y.getc()
	switch {
	default:
		goto yyrule1
	case c == '\n':
		goto yystate6
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate5
	}

yystate6:
	c = y.getc()
	goto yyrule2

yystate7:
	c = y.getc()
	switch {
	default:
		goto yyrule6
	case c == '>':
		goto yystate8
	}

yystate8:
	c = y.getc()
	goto yyrule5

yystate9:
	c = y.getc()
	switch {
	default:
		goto yyrule66
	case c == '*':
		goto yystate10
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate13
	}

yystate10:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '\\':
		goto yystate11
	}

yystate11:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'n':
		goto yystate12
	}

yystate12:
	c = y.getc()
	goto yyrule3

yystate13:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate14
	case c == '/':
		goto yystate26
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate13
	}

yystate14:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'a':
		goto yystate15
	case c == 'd':
		goto yystate19
	case c == 'j':
		goto yystate22
	case c == 'p':
		goto yystate24
	}

yystate15:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'r':
		goto yystate16
	}

yystate16:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'c':
		goto yystate17
	}

yystate17:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'h':
		goto yystate18
	}

yystate18:
	c = y.getc()
	goto yyrule66

yystate19:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'i':
		goto yystate20
	case c == 's':
		goto yystate21
	}

yystate20:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 's':
		goto yystate21
	}

yystate21:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'k':
		goto yystate18
	}

yystate22:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'p':
		goto yystate23
	}

yystate23:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'g':
		goto yystate18
	}

yystate24:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'd':
		goto yystate25
	case c == 'n':
		goto yystate23
	}

yystate25:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'f':
		goto yystate18
	}

yystate26:
	c = y.getc()
	switch {
	default:
		goto yyrule66
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate13
	}

yystate27:
	c = y.getc()
	switch {
	default:
		goto yyrule64
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9':
		goto yystate27
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate28:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'a':
		goto yystate29
	case c == 'd':
		goto yystate33
	case c == 'j':
		goto yystate36
	case c == 'p':
		goto yystate38
	}

yystate29:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'r':
		goto yystate30
	}

yystate30:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'c':
		goto yystate31
	}

yystate31:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'h':
		goto yystate32
	}

yystate32:
	c = y.getc()
	goto yyrule68

yystate33:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'i':
		goto yystate34
	case c == 's':
		goto yystate35
	}

yystate34:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 's':
		goto yystate35
	}

yystate35:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'k':
		goto yystate32
	}

yystate36:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'p':
		goto yystate37
	}

yystate37:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'g':
		goto yystate32
	}

yystate38:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'd':
		goto yystate39
	case c == 'n':
		goto yystate37
	}

yystate39:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == 'f':
		goto yystate32
	}

yystate40:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate41:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate42
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate42:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate43:
	c = y.getc()
	switch {
	default:
		goto yyrule41
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate44:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'F' || c == 'f':
		goto yystate45
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'E' || c >= 'G' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate45:
	c = y.getc()
	switch {
	default:
		goto yyrule59
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate46:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'A' || c == 'a':
		goto yystate47
	case c == 'H' || c == 'h':
		goto yystate49
	case c == 'O' || c == 'o':
		goto yystate59
	case c == 'P' || c == 'p':
		goto yystate62
	case c >= '0' && c <= '9' || c >= 'B' && c <= 'G' || c >= 'I' && c <= 'N' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'g' || c >= 'i' && c <= 'n' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate47:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate48
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate48:
	c = y.getc()
	switch {
	default:
		goto yyrule23
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate49:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'G' || c == 'g':
		goto yystate50
	case c == 'M' || c == 'm':
		goto yystate53
	case c == 'O' || c == 'o':
		goto yystate56
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'H' && c <= 'L' || c == 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'l' || c == 'n' || c >= 'p' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate50:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate51
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate51:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'P' || c == 'p':
		goto yystate52
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate52:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate53:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'O' || c == 'o':
		goto yystate54
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate54:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate55
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate55:
	c = y.getc()
	switch {
	default:
		goto yyrule21
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate56:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'W' || c == 'w':
		goto yystate57
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'V' || c >= 'X' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'v' || c >= 'x' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate57:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'N' || c == 'n':
		goto yystate58
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate58:
	c = y.getc()
	switch {
	default:
		goto yyrule31
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate59:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'N' || c == 'n':
		goto yystate60
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate60:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate61
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate61:
	c = y.getc()
	switch {
	default:
		goto yyrule51
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate62:
	c = y.getc()
	switch {
	default:
		goto yyrule28
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate63:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate64
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate64:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'L' || c == 'l':
		goto yystate65
	case c == 'S' || c == 's':
		goto yystate69
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c >= 'M' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate65:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate66
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate66:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate67
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate67:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate68
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate68:
	c = y.getc()
	switch {
	default:
		goto yyrule40
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate69:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate70:
	c = y.getc()
	switch {
	default:
		goto yyrule54
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate71:
	c = y.getc()
	switch {
	default:
		goto yyrule57
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate72
	case c == 'X' || c == 'x':
		goto yystate75
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'W' || c == 'Y' || c == 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'w' || c == 'y' || c == 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate72:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate73
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate73:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate74:
	c = y.getc()
	switch {
	default:
		goto yyrule25
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate75:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate76
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate76:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'C' || c == 'c':
		goto yystate77
	case c >= '0' && c <= '9' || c == 'A' || c == 'B' || c >= 'D' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate77:
	c = y.getc()
	switch {
	default:
		goto yyrule7
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate78:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'A' || c == 'a':
		goto yystate79
	case c == 'D' || c == 'd':
		goto yystate82
	case c == 'F' || c == 'f':
		goto yystate86
	case c == 'I' || c == 'i':
		goto yystate87
	case c == 'U' || c == 'u':
		goto yystate94
	case c >= '0' && c <= '9' || c == 'B' || c == 'C' || c == 'E' || c == 'G' || c == 'H' || c >= 'J' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c == 'b' || c == 'c' || c == 'e' || c == 'g' || c == 'h' || c >= 'j' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate79:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'S' || c == 's':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate80:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate81
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate81:
	c = y.getc()
	switch {
	default:
		goto yyrule62
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate82:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate83
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate83:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'S' || c == 's':
		goto yystate84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate84:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'K' || c == 'k':
		goto yystate85
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate85:
	c = y.getc()
	switch {
	default:
		goto yyrule11
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate86:
	c = y.getc()
	switch {
	default:
		goto yyrule60
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate87:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'L' || c == 'l':
		goto yystate88
	case c == 'N' || c == 'n':
		goto yystate91
	case c == 'T' || c == 't':
		goto yystate93
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c == 'M' || c >= 'O' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c == 'm' || c >= 'o' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate88:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate89
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate89:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9':
		goto yystate90
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate90:
	c = y.getc()
	switch {
	default:
		goto yyrule52
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9':
		goto yystate90
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate91:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate92
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate92:
	c = y.getc()
	switch {
	default:
		goto yyrule30
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate93:
	c = y.getc()
	switch {
	default:
		goto yyrule39
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate94:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'L' || c == 'l':
		goto yystate95
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c >= 'M' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate95:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'L' || c == 'l':
		goto yystate96
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c >= 'M' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate96:
	c = y.getc()
	switch {
	default:
		goto yyrule63
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate97:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate98
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate98:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'P' || c == 'p':
		goto yystate99
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate99:
	c = y.getc()
	switch {
	default:
		goto yyrule47
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate100:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate101
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate101:
	c = y.getc()
	switch {
	default:
		goto yyrule43
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9':
		goto yystate102
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate102:
	c = y.getc()
	switch {
	default:
		goto yyrule42
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9':
		goto yystate102
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate103:
	c = y.getc()
	switch {
	default:
		goto yyrule55
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate104:
	c = y.getc()
	switch {
	default:
		goto yyrule58
	case c == '.':
		goto yystate28
	case c == 'O' || c == 'o':
		goto yystate105
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate105:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'G' || c == 'g':
		goto yystate106
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'H' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate106:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate107
	case c == 'O' || c == 'o':
		goto yystate109
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate107:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'N' || c == 'n':
		goto yystate108
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate108:
	c = y.getc()
	switch {
	default:
		goto yyrule15
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate109:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'U' || c == 'u':
		goto yystate110
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate110:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate111
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate111:
	c = y.getc()
	switch {
	default:
		goto yyrule16
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate112:
	c = y.getc()
	switch {
	default:
		goto yyrule56
	case c == '.':
		goto yystate28
	case c == 'K' || c == 'k':
		goto yystate113
	case c == 'O' || c == 'o':
		goto yystate130
	case c == 'V' || c == 'v':
		goto yystate134
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'N' || c >= 'P' && c <= 'U' || c >= 'W' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'n' || c >= 'p' && c <= 'u' || c >= 'w' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate113:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate114
	case c == 'F' || c == 'f':
		goto yystate119
	case c == 'G' || c == 'g':
		goto yystate124
	case c == 'U' || c == 'u':
		goto yystate127
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c == 'E' || c >= 'H' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c == 'e' || c >= 'h' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate114:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate115
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate115:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate116
	case c == 'S' || c == 's':
		goto yystate117
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate116:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate117:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'K' || c == 'k':
		goto yystate118
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate118:
	c = y.getc()
	switch {
	default:
		goto yyrule9
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate119:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate120
	case c == 'S' || c == 's':
		goto yystate123
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate120:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'L' || c == 'l':
		goto yystate121
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c >= 'M' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate121:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate122
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate122:
	c = y.getc()
	switch {
	default:
		goto yyrule22
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate123:
	c = y.getc()
	switch {
	default:
		goto yyrule14
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate124:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate125
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate125:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'P' || c == 'p':
		goto yystate126
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate126:
	c = y.getc()
	switch {
	default:
		goto yyrule17
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate127:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'S' || c == 's':
		goto yystate128
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate128:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate129
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate129:
	c = y.getc()
	switch {
	default:
		goto yyrule19
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate130:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'U' || c == 'u':
		goto yystate131
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate131:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'N' || c == 'n':
		goto yystate132
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate132:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate133
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate133:
	c = y.getc()
	switch {
	default:
		goto yyrule12
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate134:
	c = y.getc()
	switch {
	default:
		goto yyrule29
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate135:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'A' || c == 'a':
		goto yystate136
	case c >= '0' && c <= '9' || c >= 'B' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate136:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'M' || c == 'm':
		goto yystate137
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'L' || c >= 'N' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate137:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate138
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate138:
	c = y.getc()
	switch {
	default:
		goto yyrule36
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate139:
	c = y.getc()
	switch {
	default:
		goto yyrule50
	case c == '.':
		goto yystate28
	case c == 'A' || c == 'a':
		goto yystate140
	case c == 'D' || c == 'd':
		goto yystate146
	case c >= '0' && c <= '9' || c == 'B' || c == 'C' || c >= 'E' && c <= 'Z' || c == '_' || c == 'b' || c == 'c' || c >= 'e' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate140:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate141
	case c == 'U' || c == 'u':
		goto yystate143
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'v' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate141:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'H' || c == 'h':
		goto yystate142
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'G' || c >= 'I' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate142:
	c = y.getc()
	switch {
	default:
		goto yyrule34
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate143:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'S' || c == 's':
		goto yystate144
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate144:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate145
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate145:
	c = y.getc()
	switch {
	default:
		goto yyrule8
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate146:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'W' || c == 'w':
		goto yystate147
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'V' || c >= 'X' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'v' || c >= 'x' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate147:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate148
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate148:
	c = y.getc()
	switch {
	default:
		goto yyrule46
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate149:
	c = y.getc()
	switch {
	default:
		goto yyrule49
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate150
	case c == 'F' || c == 'f':
		goto yystate153
	case c == 'M' || c == 'm':
		goto yystate154
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'G' && c <= 'L' || c >= 'N' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'g' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate150:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'N' || c == 'n':
		goto yystate151
	case c == 'P' || c == 'p':
		goto yystate152
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c == 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c == 'o' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate151:
	c = y.getc()
	switch {
	default:
		goto yyrule26
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate152:
	c = y.getc()
	switch {
	default:
		goto yyrule33
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate153:
	c = y.getc()
	switch {
	default:
		goto yyrule53
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate154:
	c = y.getc()
	switch {
	default:
		goto yyrule24
	case c == '.':
		goto yystate28
	case c == 'D' || c == 'd':
		goto yystate155
	case c == 'G' || c == 'g':
		goto yystate159
	case c == 'U' || c == 'u':
		goto yystate162
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c == 'E' || c == 'F' || c >= 'H' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c == 'e' || c == 'f' || c >= 'h' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate155:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate156
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate156:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'S' || c == 's':
		goto yystate157
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate157:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'K' || c == 'k':
		goto yystate158
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'J' || c >= 'L' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate158:
	c = y.getc()
	switch {
	default:
		goto yyrule10
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate159:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate160
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate160:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'P' || c == 'p':
		goto yystate161
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate161:
	c = y.getc()
	switch {
	default:
		goto yyrule18
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate162:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'S' || c == 's':
		goto yystate163
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate163:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate164
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate164:
	c = y.getc()
	switch {
	default:
		goto yyrule20
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate165:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate166
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate166:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'Z' || c == 'z':
		goto yystate167
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Y' || c == '_' || c >= 'a' && c <= 'y' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate167:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate168
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate168:
	c = y.getc()
	switch {
	default:
		goto yyrule35
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate169:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate170
	case c == 'Y' || c == 'y':
		goto yystate173
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'X' || c == 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'x' || c == 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate170:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'P' || c == 'p':
		goto yystate171
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate171:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'O' || c == 'o':
		goto yystate172
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate172:
	c = y.getc()
	switch {
	default:
		goto yyrule44
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate173:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'P' || c == 'p':
		goto yystate174
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'O' || c >= 'Q' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate174:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'E' || c == 'e':
		goto yystate175
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate175:
	c = y.getc()
	switch {
	default:
		goto yyrule38
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate176:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'G' || c == 'g':
		goto yystate177
	case c == 'N' || c == 'n':
		goto yystate179
	case c == 'S' || c == 's':
		goto yystate187
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'F' || c >= 'H' && c <= 'M' || c >= 'O' && c <= 'R' || c >= 'T' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'm' || c >= 'o' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate177:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'O' || c == 'o':
		goto yystate178
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate178:
	c = y.getc()
	switch {
	default:
		goto yyrule48
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate179:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'I' || c == 'i':
		goto yystate180
	case c == 'M' || c == 'm':
		goto yystate182
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'L' || c >= 'N' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'l' || c >= 'n' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate180:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate181
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate181:
	c = y.getc()
	switch {
	default:
		goto yyrule37
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate182:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'O' || c == 'o':
		goto yystate183
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate183:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'U' || c == 'u':
		goto yystate184
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate184:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'N' || c == 'n':
		goto yystate185
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'M' || c >= 'O' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate185:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'T' || c == 't':
		goto yystate186
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate186:
	c = y.getc()
	switch {
	default:
		goto yyrule13
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate187:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'R' || c == 'r':
		goto yystate188
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate188:
	c = y.getc()
	switch {
	default:
		goto yyrule45
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate189:
	c = y.getc()
	switch {
	default:
		goto yyrule65
	case c == '.':
		goto yystate28
	case c == 'F' || c == 'f':
		goto yystate190
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'E' || c >= 'G' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yystate190:
	c = y.getc()
	switch {
	default:
		goto yyrule61
	case c == '.':
		goto yystate28
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0091' || c == '±' || c == 'Ã':
		goto yystate40
	}

yyrule1: // #.*

	goto yystate0
yyrule2: // #.*\n

	goto yystate0
yyrule3: // "/*\n"

	goto yystate0
yyrule4: // [ \t\r]+

	goto yystate0
yyrule5: // "->"
	{
		lval.value = string(y.buf)
		return asignacion
		goto yystate0
	}
yyrule6: // "-"
	{
		lval.value = string(y.buf)
		return guion
		goto yystate0
	}
yyrule7: // [Ee][Xx][Ee][Cc]
	{
		lval.value = string(y.buf)
		return exec
		goto yystate0
	}
yyrule8: // [Pp][Aa][Uu][Ss][Ee]
	{
		lval.value = string(y.buf)
		return pause
		goto yystate0
	}
yyrule9: // [Mm][Kk][Dd][Ii][Ss][Kk]
	{
		lval.value = string(y.buf)
		return mkdisk
		goto yystate0
	}
yyrule10: // [Rr][Mm][Dd][Ii][Ss][Kk]
	{
		lval.value = string(y.buf)
		return rmdisk
		goto yystate0
	}
yyrule11: // [Ff][Dd][Ii][Ss][Kk]
	{
		lval.value = string(y.buf)
		return fdisk
		goto yystate0
	}
yyrule12: // [Mm][Oo][Uu][Nn][Tt]
	{
		lval.value = string(y.buf)
		return mount
		goto yystate0
	}
yyrule13: // [Uu][Nn][Mm][Oo][Uu][Nn][Tt]
	{
		lval.value = string(y.buf)
		return unmount
		goto yystate0
	}
yyrule14: // [Mm][Kk][Ff][Ss]
	{
		lval.value = string(y.buf)
		return mkfs
		goto yystate0
	}
yyrule15: // [Ll][Oo][Gg][Ii][Nn]
	{
		lval.value = string(y.buf)
		return login
		goto yystate0
	}
yyrule16: // [Ll][Oo][Gg][Oo][Uu][Tt]
	{
		lval.value = string(y.buf)
		return logout
		goto yystate0
	}
yyrule17: // [Mm][Kk][Gg][Rr][Pp]
	{
		lval.value = string(y.buf)
		return mkgrp
		goto yystate0
	}
yyrule18: // [Rr][Mm][Gg][Rr][Pp]
	{
		lval.value = string(y.buf)
		return rmgrp
		goto yystate0
	}
yyrule19: // [Mm][Kk][Uu][Ss][Rr]
	{
		lval.value = string(y.buf)
		return mkusr
		goto yystate0
	}
yyrule20: // [Rr][Mm][Uu][Ss][Rr]
	{
		lval.value = string(y.buf)
		return rmusr
		goto yystate0
	}
yyrule21: // [Cc][Hh][Mm][Oo][Dd]
	{
		lval.value = string(y.buf)
		return chmod
		goto yystate0
	}
yyrule22: // [Mm][Kk][Ff][Ii][Ll][Ee]
	{
		lval.value = string(y.buf)
		return mkfile
		goto yystate0
	}
yyrule23: // [Cc][Aa][Tt]
	{
		lval.value = string(y.buf)
		return cat
		goto yystate0
	}
yyrule24: // [Rr][Mm]
	{
		lval.value = string(y.buf)
		return rm
		goto yystate0
	}
yyrule25: // [Ee][Dd][Ii][Tt]
	{
		lval.value = string(y.buf)
		return edit
		goto yystate0
	}
yyrule26: // [Rr][Ee][Nn]
	{
		lval.value = string(y.buf)
		return ren
		goto yystate0
	}
yyrule27: // [Mm][Kk][Dd][Ii][Rr]
	{
		lval.value = string(y.buf)
		return mkdir
		goto yystate0
	}
yyrule28: // [Cc][Pp]
	{
		lval.value = string(y.buf)
		return cp
		goto yystate0
	}
yyrule29: // [Mm][Vv]
	{
		lval.value = string(y.buf)
		return mv
		goto yystate0
	}
yyrule30: // [Ff][Ii][Nn][Dd]
	{
		lval.value = string(y.buf)
		return find
		goto yystate0
	}
yyrule31: // [Cc][Hh][Oo][Ww][Nn]
	{
		lval.value = string(y.buf)
		return chown
		goto yystate0
	}
yyrule32: // [Cc][Hh][Gg][Rr][Pp]
	{
		lval.value = string(y.buf)
		return chgrp
		goto yystate0
	}
yyrule33: // [Rr][Ee][Pp]
	{
		lval.value = string(y.buf)
		return rep
		goto yystate0
	}
yyrule34: // [Pp][Aa][Tt][Hh]
	{
		lval.value = string(y.buf)
		return path
		goto yystate0
	}
yyrule35: // [Ss][Ii][Zz][Ee]
	{
		lval.value = string(y.buf)
		return size
		goto yystate0
	}
yyrule36: // [Nn][Aa][Mm][Ee]
	{
		lval.value = string(y.buf)
		return name
		goto yystate0
	}
yyrule37: // [Uu][Nn][Ii][Tt]
	{
		lval.value = string(y.buf)
		return unit
		goto yystate0
	}
yyrule38: // [Tt][Yy][Pp][Ee]
	{
		lval.value = string(y.buf)
		return rtype
		goto yystate0
	}
yyrule39: // [Ff][Ii][Tt]
	{
		lval.value = string(y.buf)
		return fit
		goto yystate0
	}
yyrule40: // [Dd][Ee][Ll][Ee][Tt][Ee]
	{
		lval.value = string(y.buf)
		return delete
		goto yystate0
	}
yyrule41: // [Aa][Dd][Dd]
	{
		lval.value = string(y.buf)
		return add
		goto yystate0
	}
yyrule42: // [Ii][Dd]{numero}
	{
		lval.value = string(y.buf)
		return idn
		goto yystate0
	}
yyrule43: // [Ii][Dd]
	{
		lval.value = string(y.buf)
		return rid
		goto yystate0
	}
yyrule44: // [Tt][Ii][Pp][Oo]
	{
		lval.value = string(y.buf)
		return tipo
		goto yystate0
	}
yyrule45: // [Uu][Ss][Rr]
	{
		lval.value = string(y.buf)
		return usr
		goto yystate0
	}
yyrule46: // [Pp][Dd][Ww][Dd]
	{
		lval.value = string(y.buf)
		return pwd
		goto yystate0
	}
yyrule47: // [Gg][Rr][Pp]
	{
		lval.value = string(y.buf)
		return grp
		goto yystate0
	}
yyrule48: // [Uu][Gg][Oo]
	{
		lval.value = string(y.buf)
		return ugo
		goto yystate0
	}
yyrule49: // [Rr]
	{
		lval.value = string(y.buf)
		return r
		goto yystate0
	}
yyrule50: // [Pp]
	{
		lval.value = string(y.buf)
		return p
		goto yystate0
	}
yyrule51: // [Cc][Oo][Nn][Tt]
	{
		lval.value = string(y.buf)
		return cont
		goto yystate0
	}
yyrule52: // [Ff][Ii][Ll][Ee]{numero}
	{
		lval.value = string(y.buf)
		return filen
		goto yystate0
	}
yyrule53: // [Rr][Ff]
	{
		lval.value = string(y.buf)
		return rf
		goto yystate0
	}
yyrule54: // [Dd][Ee][Ss][Tt]
	{
		lval.value = string(y.buf)
		return dest
		goto yystate0
	}
yyrule55: // [Kk]
	{
		lval.value = string(y.buf)
		return k
		goto yystate0
	}
yyrule56: // [Mm]
	{
		lval.value = string(y.buf)
		return m
		goto yystate0
	}
yyrule57: // [Ee]
	{
		lval.value = string(y.buf)
		return e
		goto yystate0
	}
yyrule58: // [Ll]
	{
		lval.value = string(y.buf)
		return l
		goto yystate0
	}
yyrule59: // [Bb][Ff]
	{
		lval.value = string(y.buf)
		return bf
		goto yystate0
	}
yyrule60: // [Ff][Ff]
	{
		lval.value = string(y.buf)
		return ff
		goto yystate0
	}
yyrule61: // [Ww][Ff]
	{
		lval.value = string(y.buf)
		return wf
		goto yystate0
	}
yyrule62: // [Ff][Aa][Ss][Tt]
	{
		lval.value = string(y.buf)
		return fast
		goto yystate0
	}
yyrule63: // [Ff][Uu][Ll][Ll]
	{
		lval.value = string(y.buf)
		return full
		goto yystate0
	}
yyrule64: // {numero}
	{
		lval.value = string(y.buf)
		return numero
		goto yystate0
	}
yyrule65: // {id}
	{
		lval.value = string(y.buf)
		return id
		goto yystate0
	}
yyrule66: // {rutaSimple}
	{
		lval.value = string(y.buf)
		return rutaSimple
		goto yystate0
	}
yyrule67: // {rutaCompleja}
	{
		lval.value = string(y.buf)
		return rutaCompleja
		goto yystate0
	}
yyrule68: // {archivo}
	{
		lval.value = string(y.buf)
		return archivo
		goto yystate0
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	y.empty = true
	return int(c)
}
