// Code generated by goyacc - DO NOT EDIT.

// +build ignore
package main

import __yyfmt__ "fmt"

import (
	//"bufio"
	"fmt"
	//"archivos/MIA-Proyecto1_201709454/analizador/arbol"
	"proyectos/MIAProyectoFase1/analizador/arbol"
	//"os"
)

var oParametro arbol.Parametro
var oInstruccion arbol.Instruccion
var lInstruccion []arbol.Instruccion
var lAST []arbol.AST

type yySymType struct {
	yys   int
	value string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault    = 57409
	yyEofCode    = 57344
	add          = 57382
	archivo      = 57408
	asignacion   = 57346
	bf           = 57400
	cat          = 57364
	chgrp        = 57373
	chmod        = 57362
	chown        = 57372
	cont         = 57392
	cp           = 57369
	delete       = 57381
	dest         = 57395
	e            = 57398
	edit         = 57366
	yyErrCode    = 57345
	exec         = 57348
	fast         = 57404
	fdisk        = 57352
	ff           = 57401
	filen        = 57393
	find         = 57371
	fit          = 57380
	full         = 57403
	grp          = 57388
	guion        = 57347
	id           = 57384
	idn          = 57383
	k            = 57396
	l            = 57399
	login        = 57356
	logout       = 57357
	m            = 57397
	mkdir        = 57368
	mkdisk       = 57350
	mkfile       = 57363
	mkfs         = 57355
	mkgrp        = 57358
	mkusr        = 57360
	mount        = 57353
	mv           = 57370
	name         = 57377
	numero       = 57405
	p            = 57391
	path         = 57375
	pause        = 57349
	pwd          = 57387
	r            = 57390
	ren          = 57367
	rep          = 57374
	rf           = 57394
	rm           = 57365
	rmdisk       = 57351
	rmgrp        = 57359
	rmusr        = 57361
	rtype        = 57379
	rutaCompleja = 57407
	rutaSimple   = 57406
	size         = 57376
	tipo         = 57385
	ugo          = 57389
	unit         = 57378
	unmount      = 57354
	usr          = 57386
	wf           = 57402

	yyMaxDepth = 200
	yyTabOfs   = -64
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57347: 0,  // guion (63x)
		10:    1,  // '\n' (62x)
		57346: 2,  // asignacion (10x)
		57421: 3,  // PARAMETRO_PATH (8x)
		57420: 4,  // PARAMETRO_NAME (6x)
		57344: 5,  // $end (4x)
		57348: 6,  // exec (4x)
		57352: 7,  // fdisk (4x)
		57350: 8,  // mkdisk (4x)
		57353: 9,  // mount (4x)
		57422: 10, // PARAMETRO_SIZE (4x)
		57424: 11, // PARAMETRO_UNIT (4x)
		57375: 12, // path (4x)
		57349: 13, // pause (4x)
		57351: 14, // rmdisk (4x)
		57354: 15, // unmount (4x)
		57384: 16, // id (3x)
		57377: 17, // name (3x)
		57383: 18, // idn (2x)
		57411: 19, // INSTRUCCION (2x)
		57405: 20, // numero (2x)
		57416: 21, // PARAMETRO_ADD (2x)
		57417: 22, // PARAMETRO_DELETE (2x)
		57418: 23, // PARAMETRO_FIT (2x)
		57423: 24, // PARAMETRO_TYPE (2x)
		57407: 25, // rutaCompleja (2x)
		57376: 26, // size (2x)
		57378: 27, // unit (2x)
		57382: 28, // add (1x)
		57408: 29, // archivo (1x)
		57400: 30, // bf (1x)
		57381: 31, // delete (1x)
		57398: 32, // e (1x)
		57404: 33, // fast (1x)
		57401: 34, // ff (1x)
		57380: 35, // fit (1x)
		57403: 36, // full (1x)
		57410: 37, // INICIO (1x)
		57396: 38, // k (1x)
		57399: 39, // l (1x)
		57412: 40, // LISTA_INSTRUCCION (1x)
		57413: 41, // LST_FDISK (1x)
		57414: 42, // LST_MKDIS (1x)
		57415: 43, // LST_MOUNT (1x)
		57397: 44, // m (1x)
		57391: 45, // p (1x)
		57419: 46, // PARAMETRO_IDN (1x)
		57379: 47, // rtype (1x)
		57406: 48, // rutaSimple (1x)
		57425: 49, // VALOR_DELETE (1x)
		57426: 50, // VALOR_FIT (1x)
		57427: 51, // VALOR_NAME (1x)
		57428: 52, // VALOR_PATH (1x)
		57429: 53, // VALOR_TYPE (1x)
		57430: 54, // VALOR_UNIT (1x)
		57402: 55, // wf (1x)
		57409: 56, // $default (0x)
		57364: 57, // cat (0x)
		57373: 58, // chgrp (0x)
		57362: 59, // chmod (0x)
		57372: 60, // chown (0x)
		57392: 61, // cont (0x)
		57369: 62, // cp (0x)
		57395: 63, // dest (0x)
		57366: 64, // edit (0x)
		57345: 65, // error (0x)
		57393: 66, // filen (0x)
		57371: 67, // find (0x)
		57388: 68, // grp (0x)
		57356: 69, // login (0x)
		57357: 70, // logout (0x)
		57368: 71, // mkdir (0x)
		57363: 72, // mkfile (0x)
		57355: 73, // mkfs (0x)
		57358: 74, // mkgrp (0x)
		57360: 75, // mkusr (0x)
		57370: 76, // mv (0x)
		57387: 77, // pwd (0x)
		57390: 78, // r (0x)
		57367: 79, // ren (0x)
		57374: 80, // rep (0x)
		57394: 81, // rf (0x)
		57365: 82, // rm (0x)
		57359: 83, // rmgrp (0x)
		57361: 84, // rmusr (0x)
		57385: 85, // tipo (0x)
		57389: 86, // ugo (0x)
		57386: 87, // usr (0x)
	}

	yySymNames = []string{
		"guion",
		"'\\n'",
		"asignacion",
		"PARAMETRO_PATH",
		"PARAMETRO_NAME",
		"$end",
		"exec",
		"fdisk",
		"mkdisk",
		"mount",
		"PARAMETRO_SIZE",
		"PARAMETRO_UNIT",
		"path",
		"pause",
		"rmdisk",
		"unmount",
		"id",
		"name",
		"idn",
		"INSTRUCCION",
		"numero",
		"PARAMETRO_ADD",
		"PARAMETRO_DELETE",
		"PARAMETRO_FIT",
		"PARAMETRO_TYPE",
		"rutaCompleja",
		"size",
		"unit",
		"add",
		"archivo",
		"bf",
		"delete",
		"e",
		"fast",
		"ff",
		"fit",
		"full",
		"INICIO",
		"k",
		"l",
		"LISTA_INSTRUCCION",
		"LST_FDISK",
		"LST_MKDIS",
		"LST_MOUNT",
		"m",
		"p",
		"PARAMETRO_IDN",
		"rtype",
		"rutaSimple",
		"VALOR_DELETE",
		"VALOR_FIT",
		"VALOR_NAME",
		"VALOR_PATH",
		"VALOR_TYPE",
		"VALOR_UNIT",
		"wf",
		"$default",
		"cat",
		"chgrp",
		"chmod",
		"chown",
		"cont",
		"cp",
		"dest",
		"edit",
		"error",
		"filen",
		"find",
		"grp",
		"login",
		"logout",
		"mkdir",
		"mkfile",
		"mkfs",
		"mkgrp",
		"mkusr",
		"mv",
		"pwd",
		"r",
		"ren",
		"rep",
		"rf",
		"rm",
		"rmgrp",
		"rmusr",
		"tipo",
		"ugo",
		"usr",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {37, 1},
		2:  {40, 3},
		3:  {40, 2},
		4:  {19, 1},
		5:  {19, 2},
		6:  {19, 2},
		7:  {19, 2},
		8:  {19, 2},
		9:  {19, 2},
		10: {19, 2},
		11: {43, 2},
		12: {43, 2},
		13: {43, 1},
		14: {43, 1},
		15: {41, 2},
		16: {41, 2},
		17: {41, 2},
		18: {41, 2},
		19: {41, 2},
		20: {41, 2},
		21: {41, 2},
		22: {41, 2},
		23: {41, 1},
		24: {41, 1},
		25: {41, 1},
		26: {41, 1},
		27: {41, 1},
		28: {41, 1},
		29: {41, 1},
		30: {41, 1},
		31: {42, 2},
		32: {42, 2},
		33: {42, 2},
		34: {42, 2},
		35: {42, 1},
		36: {42, 1},
		37: {42, 1},
		38: {42, 1},
		39: {3, 4},
		40: {52, 1},
		41: {52, 1},
		42: {10, 4},
		43: {4, 4},
		44: {51, 1},
		45: {51, 1},
		46: {51, 1},
		47: {11, 4},
		48: {54, 1},
		49: {54, 1},
		50: {24, 4},
		51: {53, 1},
		52: {53, 1},
		53: {53, 1},
		54: {23, 4},
		55: {50, 1},
		56: {50, 1},
		57: {50, 1},
		58: {22, 4},
		59: {49, 1},
		60: {49, 1},
		61: {21, 4},
		62: {46, 5},
		63: {46, 4},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [99][]uint16{
		// 0
		{6: 69, 72, 70, 73, 13: 68, 71, 74, 19: 67, 37: 65, 40: 66},
		{5: 64},
		{5: 63, 69, 72, 70, 73, 13: 68, 71, 74, 19: 161},
		{1: 160},
		{1: 60},
		// 5
		{148, 3: 159},
		{154, 3: 151, 152, 10: 150, 153, 42: 149},
		{148, 3: 147},
		{110, 3: 104, 108, 10: 102, 103, 21: 109, 107, 106, 105, 41: 101},
		{87, 3: 85, 86, 43: 84},
		// 10
		{76, 46: 75},
		{80, 54},
		{18: 77},
		{2: 78},
		{16: 79},
		// 15
		{1, 1},
		{18: 81},
		{2: 82},
		{16: 83},
		{2, 2},
		// 20
		{87, 55, 3: 99, 100},
		{51, 51},
		{50, 50},
		{12: 88, 17: 89},
		{2: 95},
		// 25
		{2: 90},
		{16: 93, 25: 94, 29: 92, 51: 91},
		{21, 21},
		{20, 20},
		{19, 19},
		// 30
		{18, 18},
		{25: 98, 48: 97, 52: 96},
		{25, 25},
		{24, 24},
		{23, 23},
		// 35
		{53, 53},
		{52, 52},
		{110, 56, 3: 141, 145, 10: 139, 140, 21: 146, 144, 143, 142},
		{41, 41},
		{40, 40},
		// 40
		{39, 39},
		{38, 38},
		{37, 37},
		{36, 36},
		{35, 35},
		// 45
		{34, 34},
		{12: 88, 17: 89, 26: 111, 112, 116, 31: 115, 35: 114, 47: 113},
		{2: 137},
		{2: 133},
		{2: 128},
		// 50
		{2: 123},
		{2: 119},
		{2: 117},
		{20: 118},
		{3, 3},
		// 55
		{33: 122, 36: 121, 49: 120},
		{6, 6},
		{5, 5},
		{4, 4},
		{30: 125, 34: 126, 50: 124, 55: 127},
		// 60
		{10, 10},
		{9, 9},
		{8, 8},
		{7, 7},
		{32: 131, 39: 132, 45: 130, 53: 129},
		// 65
		{14, 14},
		{13, 13},
		{12, 12},
		{11, 11},
		{38: 135, 44: 136, 54: 134},
		// 70
		{17, 17},
		{16, 16},
		{15, 15},
		{20: 138},
		{22, 22},
		// 75
		{49, 49},
		{48, 48},
		{47, 47},
		{46, 46},
		{45, 45},
		// 80
		{44, 44},
		{43, 43},
		{42, 42},
		{1: 57},
		{12: 88},
		// 85
		{154, 58, 3: 156, 157, 10: 155, 158},
		{29, 29},
		{28, 28},
		{27, 27},
		{26, 26},
		// 90
		{12: 88, 17: 89, 26: 111, 112},
		{33, 33},
		{32, 32},
		{31, 31},
		{30, 30},
		// 95
		{1: 59},
		{5: 61, 61, 61, 61, 61, 13: 61, 61, 61},
		{1: 162},
		{5: 62, 62, 62, 62, 62, 13: 62, 62, 62},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 65

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			AddAST()
			fmt.Println("AST -> ", lAST)
		}
	case 4:
		{
			fmt.Println("pausa->", yyS[yypt-0].value)
			AddInstruccion("pause")
		}
	case 5:
		{
			fmt.Println("INSTRUCCION->", yyS[yypt-1].value, yyS[yypt-0].value)
			AddParametro()
			AddInstruccion("exec")
		}
	case 6:
		{
			fmt.Println("INSTRUCCION->", yyS[yypt-1].value, yyS[yypt-0].value)
			AddInstruccion("mkdisk")
		}
	case 7:
		{
			fmt.Println("INSTRUCCION->", yyS[yypt-1].value, yyS[yypt-0].value)
			AddParametro()
			AddInstruccion("rmdisk")
		}
	case 8:
		{
			fmt.Println("INSTRUCCION->", yyS[yypt-1].value, yyS[yypt-0].value)
			AddInstruccion("fdisk")
		}
	case 9:
		{
			fmt.Println("INSTRUCCION->", yyS[yypt-1].value, yyS[yypt-0].value)
			AddInstruccion("mount")
		}
	case 10:
		{
			fmt.Println("INSTRUCCION->", yyS[yypt-1].value, yyS[yypt-0].value)
			AddInstruccion("unmount")
		}
	case 11:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 12:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 13:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 14:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 15:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 16:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 17:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 18:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 19:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 20:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 21:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 22:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 23:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 24:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 25:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 26:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 27:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 28:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 29:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 30:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 31:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 32:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 33:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 34:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 35:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 36:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 37:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 38:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 39:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 40:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 41:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 42:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 43:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 44:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 45:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 46:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 47:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 48:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 49:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 50:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 51:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 52:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 53:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 54:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 55:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 56:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 57:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 58:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 59:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 60:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 61:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 62:
		{
			yyVAL.value = yyS[yypt-4].value + yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
		}
	case 63:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}

// CrearParametro da un valor nuevo al parámetro axuliar
func CrearParametro(tipo string, valor string) {
	oParametro = arbol.Parametro{Tipo: tipo, Valor: valor}
}

// CrearInstruccion da un valor nuevo a la intruccion auxiliar
func CrearInstruccion(tipo string) {
	oInstruccion = arbol.Instruccion{Tipo: tipo}
}

// AddParametro añade el parámetro auxiliar a la lista de parametros de la instrucción actual
func AddParametro() {
	oInstruccion.Parametros = append(oInstruccion.Parametros, oParametro)
}

// AddInstruccion añade el parámetro auxiliar a la lista de parametros de la instrucción actual
func AddInstruccion(tipo string) {
	oInstruccion.Tipo = tipo
	lInstruccion = append(lInstruccion, oInstruccion)
	oInstruccion = arbol.Instruccion{}
}

// AddAST añade lista de instrucciones para ejecutar
func AddAST() {
	ast := arbol.AST{}
	ast.Instrucciones = lInstruccion
	lAST = append(lAST, ast)
}
