// Code generated by goyacc - DO NOT EDIT.

// +build ignore
package main

import __yyfmt__ "fmt"

import (
	"bufio"
	"fmt"
	"log"
	//"archivos/MIA-Proyecto1_201709454/analizador/arbol"
	"os"
	"proyectos/MIAProyectoFase1/analizador/arbol"
)

var oParametro arbol.Parametro
var oInstruccion arbol.Instruccion
var lInstruccion []arbol.Instruccion
var lAST []arbol.AST
var auxPath string

type yySymType struct {
	yys   int
	value string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault    = 57410
	yyEofCode    = 57344
	add          = 57382
	archivo      = 57409
	asignacion   = 57346
	bf           = 57400
	cat          = 57364
	chgrp        = 57373
	chmod        = 57362
	chown        = 57372
	cont         = 57392
	cp           = 57369
	delete       = 57381
	dest         = 57395
	e            = 57398
	edit         = 57366
	yyErrCode    = 57345
	exec         = 57348
	fast         = 57404
	fdisk        = 57352
	ff           = 57401
	filen        = 57393
	find         = 57371
	fit          = 57380
	full         = 57403
	grp          = 57388
	guion        = 57347
	id           = 57384
	idn          = 57383
	k            = 57396
	l            = 57399
	login        = 57356
	logout       = 57357
	m            = 57397
	mkdir        = 57368
	mkdisk       = 57350
	mkfile       = 57363
	mkfs         = 57355
	mkgrp        = 57358
	mkusr        = 57360
	mount        = 57353
	mv           = 57370
	name         = 57377
	numero       = 57406
	p            = 57391
	path         = 57375
	pause        = 57349
	pwd          = 57387
	r            = 57390
	ren          = 57367
	rep          = 57374
	rf           = 57394
	rid          = 57405
	rm           = 57365
	rmdisk       = 57351
	rmgrp        = 57359
	rmusr        = 57361
	rtype        = 57379
	rutaCompleja = 57408
	rutaSimple   = 57407
	size         = 57376
	tipo         = 57385
	ugo          = 57389
	unit         = 57378
	unmount      = 57354
	usr          = 57386
	wf           = 57402

	yyMaxDepth = 200
	yyTabOfs   = -103
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57347: 0,  // guion (104x)
		57344: 1,  // $end (100x)
		57348: 2,  // exec (100x)
		57352: 3,  // fdisk (100x)
		57356: 4,  // login (100x)
		57357: 5,  // logout (100x)
		57350: 6,  // mkdisk (100x)
		57355: 7,  // mkfs (100x)
		57358: 8,  // mkgrp (100x)
		57360: 9,  // mkusr (100x)
		57353: 10, // mount (100x)
		57349: 11, // pause (100x)
		57374: 12, // rep (100x)
		57351: 13, // rmdisk (100x)
		57354: 14, // unmount (100x)
		57346: 15, // asignacion (14x)
		57429: 16, // PARAMETRO_PATH (10x)
		57426: 17, // PARAMETRO_ID (9x)
		57428: 18, // PARAMETRO_NAME (6x)
		57384: 19, // id (5x)
		57375: 20, // path (5x)
		57405: 21, // rid (5x)
		57377: 22, // name (4x)
		57406: 23, // numero (4x)
		57424: 24, // PARAMETRO_FIT (4x)
		57430: 25, // PARAMETRO_PWD (4x)
		57431: 26, // PARAMETRO_SIZE (4x)
		57434: 27, // PARAMETRO_UNIT (4x)
		57435: 28, // PARAMETRO_USR (4x)
		57408: 29, // rutaCompleja (3x)
		57404: 30, // fast (2x)
		57380: 31, // fit (2x)
		57403: 32, // full (2x)
		57412: 33, // INSTRUCCION (2x)
		57422: 34, // PARAMETRO_ADD (2x)
		57423: 35, // PARAMETRO_DELETE (2x)
		57425: 36, // PARAMETRO_GRP (2x)
		57432: 37, // PARAMETRO_TYPE (2x)
		57433: 38, // PARAMETRO_TYPE_FS (2x)
		57379: 39, // rtype (2x)
		57376: 40, // size (2x)
		57378: 41, // unit (2x)
		57436: 42, // VALOR_DELETE (2x)
		57382: 43, // add (1x)
		57409: 44, // archivo (1x)
		57400: 45, // bf (1x)
		57381: 46, // delete (1x)
		57398: 47, // e (1x)
		57401: 48, // ff (1x)
		57411: 49, // INICIO (1x)
		57396: 50, // k (1x)
		57399: 51, // l (1x)
		57413: 52, // LISTA_INSTRUCCION (1x)
		57414: 53, // LST_FDISK (1x)
		57415: 54, // LST_LOGIN (1x)
		57416: 55, // LST_MKDIS (1x)
		57417: 56, // LST_MKFS (1x)
		57418: 57, // LST_MKGRP (1x)
		57419: 58, // LST_MKUSR (1x)
		57420: 59, // LST_MOUNT (1x)
		57421: 60, // LST_REP (1x)
		57397: 61, // m (1x)
		57391: 62, // p (1x)
		57387: 63, // pwd (1x)
		57407: 64, // rutaSimple (1x)
		57386: 65, // usr (1x)
		57437: 66, // VALOR_FIT (1x)
		57438: 67, // VALOR_NAME (1x)
		57439: 68, // VALOR_PATH (1x)
		57440: 69, // VALOR_TYPE (1x)
		57441: 70, // VALOR_UNIT (1x)
		57402: 71, // wf (1x)
		57410: 72, // $default (0x)
		57364: 73, // cat (0x)
		57373: 74, // chgrp (0x)
		57362: 75, // chmod (0x)
		57372: 76, // chown (0x)
		57392: 77, // cont (0x)
		57369: 78, // cp (0x)
		57395: 79, // dest (0x)
		57366: 80, // edit (0x)
		57345: 81, // error (0x)
		57393: 82, // filen (0x)
		57371: 83, // find (0x)
		57388: 84, // grp (0x)
		57383: 85, // idn (0x)
		57368: 86, // mkdir (0x)
		57363: 87, // mkfile (0x)
		57370: 88, // mv (0x)
		57427: 89, // PARAMETRO_IDN (0x)
		57390: 90, // r (0x)
		57367: 91, // ren (0x)
		57394: 92, // rf (0x)
		57365: 93, // rm (0x)
		57359: 94, // rmgrp (0x)
		57361: 95, // rmusr (0x)
		57385: 96, // tipo (0x)
		57389: 97, // ugo (0x)
	}

	yySymNames = []string{
		"guion",
		"$end",
		"exec",
		"fdisk",
		"login",
		"logout",
		"mkdisk",
		"mkfs",
		"mkgrp",
		"mkusr",
		"mount",
		"pause",
		"rep",
		"rmdisk",
		"unmount",
		"asignacion",
		"PARAMETRO_PATH",
		"PARAMETRO_ID",
		"PARAMETRO_NAME",
		"id",
		"path",
		"rid",
		"name",
		"numero",
		"PARAMETRO_FIT",
		"PARAMETRO_PWD",
		"PARAMETRO_SIZE",
		"PARAMETRO_UNIT",
		"PARAMETRO_USR",
		"rutaCompleja",
		"fast",
		"fit",
		"full",
		"INSTRUCCION",
		"PARAMETRO_ADD",
		"PARAMETRO_DELETE",
		"PARAMETRO_GRP",
		"PARAMETRO_TYPE",
		"PARAMETRO_TYPE_FS",
		"rtype",
		"size",
		"unit",
		"VALOR_DELETE",
		"add",
		"archivo",
		"bf",
		"delete",
		"e",
		"ff",
		"INICIO",
		"k",
		"l",
		"LISTA_INSTRUCCION",
		"LST_FDISK",
		"LST_LOGIN",
		"LST_MKDIS",
		"LST_MKFS",
		"LST_MKGRP",
		"LST_MKUSR",
		"LST_MOUNT",
		"LST_REP",
		"m",
		"p",
		"pwd",
		"rutaSimple",
		"usr",
		"VALOR_FIT",
		"VALOR_NAME",
		"VALOR_PATH",
		"VALOR_TYPE",
		"VALOR_UNIT",
		"wf",
		"$default",
		"cat",
		"chgrp",
		"chmod",
		"chown",
		"cont",
		"cp",
		"dest",
		"edit",
		"error",
		"filen",
		"find",
		"grp",
		"idn",
		"mkdir",
		"mkfile",
		"mv",
		"PARAMETRO_IDN",
		"r",
		"ren",
		"rf",
		"rm",
		"rmgrp",
		"rmusr",
		"tipo",
		"ugo",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:   {0, 1},
		1:   {49, 1},
		2:   {52, 2},
		3:   {52, 1},
		4:   {33, 1},
		5:   {33, 1},
		6:   {33, 2},
		7:   {33, 2},
		8:   {33, 2},
		9:   {33, 2},
		10:  {33, 2},
		11:  {33, 2},
		12:  {33, 2},
		13:  {33, 2},
		14:  {33, 2},
		15:  {33, 2},
		16:  {33, 2},
		17:  {58, 2},
		18:  {58, 2},
		19:  {58, 2},
		20:  {58, 1},
		21:  {58, 1},
		22:  {58, 1},
		23:  {57, 2},
		24:  {57, 1},
		25:  {54, 2},
		26:  {54, 2},
		27:  {54, 2},
		28:  {54, 1},
		29:  {54, 1},
		30:  {54, 1},
		31:  {56, 2},
		32:  {56, 2},
		33:  {56, 1},
		34:  {56, 1},
		35:  {60, 2},
		36:  {60, 2},
		37:  {60, 2},
		38:  {60, 1},
		39:  {60, 1},
		40:  {60, 1},
		41:  {59, 2},
		42:  {59, 2},
		43:  {59, 1},
		44:  {59, 1},
		45:  {53, 2},
		46:  {53, 2},
		47:  {53, 2},
		48:  {53, 2},
		49:  {53, 2},
		50:  {53, 2},
		51:  {53, 2},
		52:  {53, 2},
		53:  {53, 1},
		54:  {53, 1},
		55:  {53, 1},
		56:  {53, 1},
		57:  {53, 1},
		58:  {53, 1},
		59:  {53, 1},
		60:  {53, 1},
		61:  {55, 2},
		62:  {55, 2},
		63:  {55, 2},
		64:  {55, 2},
		65:  {55, 1},
		66:  {55, 1},
		67:  {55, 1},
		68:  {55, 1},
		69:  {36, 4},
		70:  {16, 4},
		71:  {68, 1},
		72:  {68, 1},
		73:  {26, 4},
		74:  {18, 4},
		75:  {67, 1},
		76:  {67, 1},
		77:  {67, 1},
		78:  {28, 4},
		79:  {25, 4},
		80:  {25, 4},
		81:  {28, 4},
		82:  {27, 4},
		83:  {70, 1},
		84:  {70, 1},
		85:  {37, 4},
		86:  {69, 1},
		87:  {69, 1},
		88:  {69, 1},
		89:  {24, 4},
		90:  {66, 1},
		91:  {66, 1},
		92:  {66, 1},
		93:  {35, 4},
		94:  {38, 4},
		95:  {42, 1},
		96:  {42, 1},
		97:  {34, 4},
		98:  {34, 5},
		99:  {89, 5},
		100: {89, 4},
		101: {17, 5},
		102: {17, 4},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [151][]uint16{
		// 0
		{2: 109, 112, 117, 108, 110, 116, 118, 119, 113, 107, 115, 111, 114, 33: 106, 49: 104, 52: 105},
		{1: 103},
		{1: 102, 109, 112, 117, 108, 110, 116, 118, 119, 113, 107, 115, 111, 114, 33: 253},
		{1: 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100},
		{1: 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99},
		// 5
		{1: 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98},
		{241, 16: 252},
		{247, 16: 244, 24: 246, 26: 243, 245, 55: 242},
		{241, 16: 240},
		{203, 16: 197, 18: 201, 24: 199, 26: 195, 196, 34: 202, 200, 37: 198, 53: 194},
		// 10
		{191, 16: 189, 18: 190, 59: 188},
		{187, 17: 186},
		{171, 16: 169, 170, 168, 60: 167},
		{159, 17: 157, 38: 158, 56: 156},
		{124, 17: 152, 25: 151, 28: 150, 54: 149},
		// 15
		{144, 36: 143, 57: 142},
		{124, 17: 123, 25: 122, 28: 121, 58: 120},
		{124, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 17: 141, 25: 140, 28: 139},
		{83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83},
		{82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82},
		// 20
		{135, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81},
		{21: 127, 63: 126, 65: 125},
		{15: 133},
		{15: 130},
		{15: 128},
		// 25
		{19: 129},
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
		{19: 131, 23: 132},
		{24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24},
		{23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23},
		// 30
		{19: 134},
		{25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25},
		{21: 136},
		{15: 137},
		{19: 138},
		// 35
		{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
		{86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86},
		{85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85},
		{135, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84},
		{144, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 36: 148},
		// 40
		{79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79},
		{22: 145},
		{15: 146},
		{29: 147},
		{34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34},
		// 45
		{80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80},
		{124, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 17: 155, 25: 154, 28: 153},
		{75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75},
		{74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74},
		{135, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73},
		// 50
		{78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78},
		{77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77},
		{135, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76},
		{159, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 17: 165, 38: 166},
		{135, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70},
		// 55
		{69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69},
		{21: 127, 39: 160},
		{15: 161},
		{30: 164, 32: 163, 42: 162},
		{9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
		// 60
		{8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8},
		{7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
		{135, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72},
		{71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71},
		{171, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 16: 184, 185, 183},
		// 65
		{65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65},
		{64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64},
		{135, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63},
		{20: 172, 127, 173},
		{15: 179},
		// 70
		{15: 174},
		{19: 177, 29: 178, 44: 176, 67: 175},
		{29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29},
		{28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28},
		{27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27},
		// 75
		{26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26},
		{29: 182, 64: 181, 68: 180},
		{33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33},
		{32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32},
		{31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31},
		// 80
		{68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68},
		{67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67},
		{135, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66},
		{135, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92},
		{21: 127},
		// 85
		{191, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 16: 192, 18: 193},
		{60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60},
		{59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59},
		{20: 172, 22: 173},
		{62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62},
		// 90
		{61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61},
		{203, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 16: 234, 18: 238, 24: 236, 26: 232, 233, 34: 239, 237, 37: 235},
		{50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50},
		{49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49},
		{48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48},
		// 95
		{47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47},
		{46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46},
		{45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45},
		{44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44},
		{43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43},
		// 100
		{20: 172, 22: 173, 31: 207, 39: 206, 204, 205, 43: 209, 46: 208},
		{15: 230},
		{15: 226},
		{15: 221},
		{15: 216},
		// 105
		{15: 214},
		{15: 210},
		{212, 23: 211},
		{6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6},
		{23: 213},
		// 110
		{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
		{30: 164, 32: 163, 42: 215},
		{10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10},
		{45: 218, 48: 219, 66: 217, 71: 220},
		{14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14},
		// 115
		{13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13},
		{12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12},
		{11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11},
		{47: 224, 51: 225, 62: 223, 69: 222},
		{18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18},
		// 120
		{17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17},
		{16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16},
		{15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15},
		{50: 228, 61: 229, 70: 227},
		{21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21},
		// 125
		{20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20},
		{19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19},
		{23: 231},
		{30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30},
		{58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58},
		// 130
		{57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57},
		{56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56},
		{55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55},
		{54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54},
		{53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53},
		// 135
		{52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52},
		{51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51},
		{1: 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95},
		{20: 172},
		{247, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 16: 249, 24: 251, 26: 248, 250},
		// 140
		{38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38},
		{37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37},
		{36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36},
		{35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35},
		{20: 172, 31: 207, 40: 204, 205},
		// 145
		{42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42},
		{41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41},
		{40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40},
		{39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39},
		{1: 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97},
		// 150
		{1: 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 81

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			AddAST()
		}
	case 4:
		{
			AddInstruccion("pause")
		}
	case 5:
		{
			AddInstruccion("logout")
		}
	case 6:
		{
			EjecutarExec()
		}
	case 7:
		{
			AddInstruccion("mkdisk")
		}
	case 8:
		{
			AddParametro()
			AddInstruccion("rmdisk")
		}
	case 9:
		{
			AddInstruccion("fdisk")
		}
	case 10:
		{
			AddInstruccion("mount")
		}
	case 11:
		{
			AddParametro()
			AddInstruccion("unmount")
		}
	case 12:
		{
			AddInstruccion("rep")
		}
	case 13:
		{
			AddInstruccion("mkfs")
		}
	case 14:
		{
			AddInstruccion("login")
		}
	case 15:
		{
			AddInstruccion("mkgrp")
		}
	case 16:
		{
			AddInstruccion("mkusr")
		}
	case 17:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 18:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 19:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 20:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 21:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 22:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 23:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 24:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 25:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 26:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 27:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 28:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 29:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 30:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 31:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 32:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 33:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 34:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 35:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 36:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 37:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 38:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 39:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 40:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 41:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 42:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 43:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 44:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 45:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 46:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 47:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 48:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 49:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 50:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 51:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 52:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 53:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 54:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 55:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 56:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 57:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 58:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 59:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 60:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 61:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 62:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 63:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 64:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 65:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 66:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 67:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 68:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 69:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 70:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			auxPath = yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 71:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 72:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 73:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 74:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 75:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 76:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 77:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 78:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 79:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 80:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 81:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 82:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 83:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 84:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 85:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 86:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 87:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 88:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 89:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 90:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 91:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 92:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 93:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 94:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 95:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 96:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 97:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 98:
		{
			yyVAL.value = yyS[yypt-4].value + yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-3].value, "-"+yyS[yypt-0].value)
		}
	case 99:
		{
			yyVAL.value = yyS[yypt-4].value + yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
		}
	case 100:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
		}
	case 101:
		{
			yyVAL.value = yyS[yypt-4].value + yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 102:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}

// CrearParametro da un valor nuevo al parámetro axuliar
func CrearParametro(tipo string, valor string) {
	oParametro = arbol.Parametro{Tipo: tipo, Valor: valor}
}

// CrearInstruccion da un valor nuevo a la intruccion auxiliar
func CrearInstruccion(tipo string) {
	oInstruccion = arbol.Instruccion{Tipo: tipo}
}

// AddParametro añade el parámetro auxiliar a la lista de parametros de la instrucción actual
func AddParametro() {
	oInstruccion.Parametros = append(oInstruccion.Parametros, oParametro)
}

// AddInstruccion añade el parámetro auxiliar a la lista de parametros de la instrucción actual
func AddInstruccion(tipo string) {
	oInstruccion.Tipo = tipo
	lInstruccion = append(lInstruccion, oInstruccion)
	oInstruccion = arbol.Instruccion{}
}

// AddAST añade lista de instrucciones para ejecutar
func AddAST() {
	ast := arbol.AST{}
	ast.Instrucciones = lInstruccion
	lInstruccion = []arbol.Instruccion{}
	lAST = append(lAST, ast)
}

func EjecutarExec() {
	if file, err := os.Open(auxPath); err == nil {
		yyParse(newLexer(bufio.NewReader(file)))

		ast := lAST[len(lAST)-1]
		ast.EjecutarAST()
		lAST = lAST[:len(lAST)-1]

		fmt.Println("Se ha ejecutado el archivo con èxito")
	} else {
		fmt.Println("No se ha podido abrir el archivo")
		log.Panic(err)
	}
}
