// Code generated by goyacc - DO NOT EDIT.

// +build ignore
package main

import __yyfmt__ "fmt"

import (
	"bufio"
	"fmt"
	"log"
	//"archivos/MIA-Proyecto1_201709454/analizador/arbol"
	"os"
	"proyectos/MIAProyectoFase1/analizador/arbol"
)

var oParametro arbol.Parametro
var oInstruccion arbol.Instruccion
var lInstruccion []arbol.Instruccion
var lAST []arbol.AST
var auxPath string

type yySymType struct {
	yys   int
	value string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault    = 57411
	yyEofCode    = 57344
	add          = 57382
	archivo      = 57409
	asignacion   = 57346
	bf           = 57400
	cat          = 57364
	chgrp        = 57373
	chmod        = 57362
	chown        = 57372
	cont         = 57392
	cp           = 57369
	delete       = 57381
	dest         = 57395
	e            = 57398
	edit         = 57366
	yyErrCode    = 57345
	exec         = 57348
	fast         = 57404
	fdisk        = 57352
	ff           = 57401
	filen        = 57393
	find         = 57371
	fit          = 57380
	full         = 57403
	grp          = 57388
	guion        = 57347
	id           = 57384
	idn          = 57383
	k            = 57396
	l            = 57399
	login        = 57356
	logout       = 57357
	m            = 57397
	mkdir        = 57368
	mkdisk       = 57350
	mkfile       = 57363
	mkfs         = 57355
	mkgrp        = 57358
	mkusr        = 57360
	mount        = 57353
	mv           = 57370
	name         = 57377
	numero       = 57406
	p            = 57391
	path         = 57375
	pause        = 57349
	pwd          = 57387
	r            = 57390
	rem          = 57365
	ren          = 57367
	rep          = 57374
	rf           = 57394
	rid          = 57405
	rmdisk       = 57351
	rmgrp        = 57359
	rmusr        = 57361
	rruta        = 57410
	rtype        = 57379
	rutaCompleja = 57408
	rutaSimple   = 57407
	size         = 57376
	tipo         = 57385
	ugo          = 57389
	unit         = 57378
	unmount      = 57354
	usr          = 57386
	wf           = 57402

	yyMaxDepth = 200
	yyTabOfs   = -131
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57347: 0,   // guion (137x)
		57344: 1,   // $end (128x)
		57364: 2,   // cat (128x)
		57348: 3,   // exec (128x)
		57352: 4,   // fdisk (128x)
		57356: 5,   // login (128x)
		57357: 6,   // logout (128x)
		57368: 7,   // mkdir (128x)
		57350: 8,   // mkdisk (128x)
		57363: 9,   // mkfile (128x)
		57355: 10,  // mkfs (128x)
		57358: 11,  // mkgrp (128x)
		57360: 12,  // mkusr (128x)
		57353: 13,  // mount (128x)
		57349: 14,  // pause (128x)
		57365: 15,  // rem (128x)
		57367: 16,  // ren (128x)
		57374: 17,  // rep (128x)
		57351: 18,  // rmdisk (128x)
		57354: 19,  // unmount (128x)
		57437: 20,  // PARAMETRO_PATH (18x)
		57346: 21,  // asignacion (16x)
		57433: 22,  // PARAMETRO_ID (9x)
		57435: 23,  // PARAMETRO_NAME (8x)
		57440: 24,  // PARAMETRO_SIZE (8x)
		57375: 25,  // path (6x)
		57384: 26,  // id (5x)
		57405: 27,  // rid (5x)
		57408: 28,  // rutaCompleja (5x)
		57377: 29,  // name (4x)
		57406: 30,  // numero (4x)
		57431: 31,  // PARAMETRO_FIT (4x)
		57436: 32,  // PARAMETRO_P (4x)
		57438: 33,  // PARAMETRO_PWD (4x)
		57443: 34,  // PARAMETRO_UNIT (4x)
		57444: 35,  // PARAMETRO_USR (4x)
		57407: 36,  // rutaSimple (3x)
		57376: 37,  // size (3x)
		57448: 38,  // VALOR_PATH (3x)
		57404: 39,  // fast (2x)
		57380: 40,  // fit (2x)
		57403: 41,  // full (2x)
		57413: 42,  // INSTRUCCION (2x)
		57420: 43,  // LST_MKFILE (2x)
		57391: 44,  // p (2x)
		57428: 45,  // PARAMETRO_ADD (2x)
		57429: 46,  // PARAMETRO_DELETE (2x)
		57430: 47,  // PARAMETRO_FILEN (2x)
		57432: 48,  // PARAMETRO_GRP (2x)
		57439: 49,  // PARAMETRO_RUTA (2x)
		57441: 50,  // PARAMETRO_TYPE (2x)
		57442: 51,  // PARAMETRO_TYPE_FS (2x)
		57379: 52,  // rtype (2x)
		57378: 53,  // unit (2x)
		57445: 54,  // VALOR_DELETE (2x)
		57382: 55,  // add (1x)
		57409: 56,  // archivo (1x)
		57400: 57,  // bf (1x)
		57381: 58,  // delete (1x)
		57398: 59,  // e (1x)
		57401: 60,  // ff (1x)
		57393: 61,  // filen (1x)
		57412: 62,  // INICIO (1x)
		57396: 63,  // k (1x)
		57399: 64,  // l (1x)
		57414: 65,  // LISTA_INSTRUCCION (1x)
		57415: 66,  // LST_CAT (1x)
		57416: 67,  // LST_FDISK (1x)
		57417: 68,  // LST_LOGIN (1x)
		57418: 69,  // LST_MKDIR (1x)
		57419: 70,  // LST_MKDIS (1x)
		57421: 71,  // LST_MKFS (1x)
		57422: 72,  // LST_MKGRP (1x)
		57423: 73,  // LST_MKUSR (1x)
		57424: 74,  // LST_MOUNT (1x)
		57425: 75,  // LST_REM (1x)
		57426: 76,  // LST_REN (1x)
		57427: 77,  // LST_REP (1x)
		57397: 78,  // m (1x)
		57387: 79,  // pwd (1x)
		57410: 80,  // rruta (1x)
		57386: 81,  // usr (1x)
		57446: 82,  // VALOR_FIT (1x)
		57447: 83,  // VALOR_NAME (1x)
		57449: 84,  // VALOR_TYPE (1x)
		57450: 85,  // VALOR_UNIT (1x)
		57402: 86,  // wf (1x)
		57411: 87,  // $default (0x)
		57373: 88,  // chgrp (0x)
		57362: 89,  // chmod (0x)
		57372: 90,  // chown (0x)
		57392: 91,  // cont (0x)
		57369: 92,  // cp (0x)
		57395: 93,  // dest (0x)
		57366: 94,  // edit (0x)
		57345: 95,  // error (0x)
		57371: 96,  // find (0x)
		57388: 97,  // grp (0x)
		57383: 98,  // idn (0x)
		57370: 99,  // mv (0x)
		57434: 100, // PARAMETRO_IDN (0x)
		57390: 101, // r (0x)
		57394: 102, // rf (0x)
		57359: 103, // rmgrp (0x)
		57361: 104, // rmusr (0x)
		57385: 105, // tipo (0x)
		57389: 106, // ugo (0x)
	}

	yySymNames = []string{
		"guion",
		"$end",
		"cat",
		"exec",
		"fdisk",
		"login",
		"logout",
		"mkdir",
		"mkdisk",
		"mkfile",
		"mkfs",
		"mkgrp",
		"mkusr",
		"mount",
		"pause",
		"rem",
		"ren",
		"rep",
		"rmdisk",
		"unmount",
		"PARAMETRO_PATH",
		"asignacion",
		"PARAMETRO_ID",
		"PARAMETRO_NAME",
		"PARAMETRO_SIZE",
		"path",
		"id",
		"rid",
		"rutaCompleja",
		"name",
		"numero",
		"PARAMETRO_FIT",
		"PARAMETRO_P",
		"PARAMETRO_PWD",
		"PARAMETRO_UNIT",
		"PARAMETRO_USR",
		"rutaSimple",
		"size",
		"VALOR_PATH",
		"fast",
		"fit",
		"full",
		"INSTRUCCION",
		"LST_MKFILE",
		"p",
		"PARAMETRO_ADD",
		"PARAMETRO_DELETE",
		"PARAMETRO_FILEN",
		"PARAMETRO_GRP",
		"PARAMETRO_RUTA",
		"PARAMETRO_TYPE",
		"PARAMETRO_TYPE_FS",
		"rtype",
		"unit",
		"VALOR_DELETE",
		"add",
		"archivo",
		"bf",
		"delete",
		"e",
		"ff",
		"filen",
		"INICIO",
		"k",
		"l",
		"LISTA_INSTRUCCION",
		"LST_CAT",
		"LST_FDISK",
		"LST_LOGIN",
		"LST_MKDIR",
		"LST_MKDIS",
		"LST_MKFS",
		"LST_MKGRP",
		"LST_MKUSR",
		"LST_MOUNT",
		"LST_REM",
		"LST_REN",
		"LST_REP",
		"m",
		"pwd",
		"rruta",
		"usr",
		"VALOR_FIT",
		"VALOR_NAME",
		"VALOR_TYPE",
		"VALOR_UNIT",
		"wf",
		"$default",
		"chgrp",
		"chmod",
		"chown",
		"cont",
		"cp",
		"dest",
		"edit",
		"error",
		"find",
		"grp",
		"idn",
		"mv",
		"PARAMETRO_IDN",
		"r",
		"rf",
		"rmgrp",
		"rmusr",
		"tipo",
		"ugo",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:   {0, 1},
		1:   {62, 1},
		2:   {65, 2},
		3:   {65, 1},
		4:   {42, 1},
		5:   {42, 1},
		6:   {42, 2},
		7:   {42, 2},
		8:   {42, 2},
		9:   {42, 2},
		10:  {42, 2},
		11:  {42, 2},
		12:  {42, 2},
		13:  {42, 2},
		14:  {42, 2},
		15:  {42, 2},
		16:  {42, 2},
		17:  {42, 2},
		18:  {42, 2},
		19:  {42, 2},
		20:  {42, 2},
		21:  {42, 2},
		22:  {76, 2},
		23:  {76, 2},
		24:  {76, 1},
		25:  {76, 1},
		26:  {66, 2},
		27:  {66, 1},
		28:  {75, 2},
		29:  {75, 1},
		30:  {69, 2},
		31:  {69, 2},
		32:  {69, 1},
		33:  {69, 1},
		34:  {43, 2},
		35:  {43, 2},
		36:  {43, 2},
		37:  {43, 1},
		38:  {43, 1},
		39:  {43, 1},
		40:  {73, 2},
		41:  {73, 2},
		42:  {73, 2},
		43:  {73, 1},
		44:  {73, 1},
		45:  {73, 1},
		46:  {72, 2},
		47:  {72, 1},
		48:  {68, 2},
		49:  {68, 2},
		50:  {68, 2},
		51:  {68, 1},
		52:  {68, 1},
		53:  {68, 1},
		54:  {71, 2},
		55:  {71, 2},
		56:  {71, 1},
		57:  {71, 1},
		58:  {77, 2},
		59:  {77, 2},
		60:  {77, 2},
		61:  {77, 2},
		62:  {77, 1},
		63:  {77, 1},
		64:  {77, 1},
		65:  {77, 1},
		66:  {74, 2},
		67:  {74, 2},
		68:  {74, 1},
		69:  {74, 1},
		70:  {67, 2},
		71:  {67, 2},
		72:  {67, 2},
		73:  {67, 2},
		74:  {67, 2},
		75:  {67, 2},
		76:  {67, 2},
		77:  {67, 2},
		78:  {67, 1},
		79:  {67, 1},
		80:  {67, 1},
		81:  {67, 1},
		82:  {67, 1},
		83:  {67, 1},
		84:  {67, 1},
		85:  {67, 1},
		86:  {70, 2},
		87:  {70, 2},
		88:  {70, 2},
		89:  {70, 2},
		90:  {70, 1},
		91:  {70, 1},
		92:  {70, 1},
		93:  {70, 1},
		94:  {48, 4},
		95:  {47, 4},
		96:  {20, 4},
		97:  {49, 4},
		98:  {38, 1},
		99:  {38, 1},
		100: {24, 4},
		101: {23, 4},
		102: {83, 1},
		103: {83, 1},
		104: {83, 1},
		105: {35, 4},
		106: {33, 4},
		107: {33, 4},
		108: {35, 4},
		109: {34, 4},
		110: {85, 1},
		111: {85, 1},
		112: {50, 4},
		113: {84, 1},
		114: {84, 1},
		115: {84, 1},
		116: {31, 4},
		117: {32, 2},
		118: {82, 1},
		119: {82, 1},
		120: {82, 1},
		121: {46, 4},
		122: {51, 4},
		123: {54, 1},
		124: {54, 1},
		125: {45, 4},
		126: {45, 5},
		127: {100, 5},
		128: {100, 4},
		129: {22, 5},
		130: {22, 4},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [191][]uint16{
		// 0
		{2: 151, 137, 140, 145, 136, 149, 138, 148, 144, 146, 147, 141, 135, 150, 152, 143, 139, 142, 42: 134, 62: 132, 65: 133},
		{1: 131},
		{1: 130, 151, 137, 140, 145, 136, 149, 138, 148, 144, 146, 147, 141, 135, 150, 152, 143, 139, 142, 42: 321},
		{1: 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128},
		{1: 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127},
		// 5
		{1: 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126},
		{179, 20: 320},
		{315, 20: 312, 24: 311, 31: 314, 34: 313, 70: 310},
		{179, 20: 309},
		{275, 20: 269, 23: 273, 267, 31: 271, 34: 268, 45: 274, 272, 50: 270, 67: 266},
		// 10
		{156, 20: 262, 23: 263, 74: 261},
		{260, 22: 259},
		{251, 20: 248, 22: 249, 247, 49: 250, 77: 246},
		{238, 22: 236, 51: 237, 71: 235},
		{203, 22: 231, 33: 230, 35: 229, 68: 228},
		// 15
		{223, 48: 222, 72: 221},
		{203, 22: 202, 33: 201, 35: 200, 73: 199},
		{186, 20: 195, 24: 185, 32: 196, 43: 194},
		{186, 20: 183, 24: 185, 32: 184, 43: 182, 69: 181},
		{179, 20: 178, 75: 177},
		// 20
		{172, 47: 171, 66: 170},
		{156, 20: 154, 23: 155, 76: 153},
		{156, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 168, 23: 169},
		{107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107},
		{106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106},
		// 25
		{25: 157, 29: 158},
		{21: 164},
		{21: 159},
		{26: 162, 28: 163, 56: 161, 83: 160},
		{30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30},
		// 30
		{29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29},
		{28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28},
		{27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27},
		{28: 167, 36: 166, 38: 165},
		{35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35},
		// 35
		{33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33},
		{32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32},
		{109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109},
		{108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108},
		{172, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 47: 176},
		// 40
		{104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104},
		{61: 173},
		{21: 174},
		{28: 167, 36: 166, 38: 175},
		{36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36},
		// 45
		{105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105},
		{179, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 180},
		{102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102},
		{25: 157},
		{103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103},
		// 50
		{1: 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113},
		{186, 20: 191, 24: 193, 32: 192},
		{94, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99},
		{92, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98},
		{93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93},
		// 55
		{25: 157, 37: 187, 44: 188},
		{21: 189},
		{14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14},
		{30: 190},
		{31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31},
		// 60
		{97, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101},
		{95, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100},
		{96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96},
		{186, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 197, 24: 193, 32: 198},
		{94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94},
		// 65
		{92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92},
		{97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97},
		{95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95},
		{203, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 22: 220, 33: 219, 35: 218},
		{88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88},
		// 70
		{87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87},
		{214, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86},
		{27: 206, 79: 205, 81: 204},
		{21: 212},
		{21: 209},
		// 75
		{21: 207},
		{26: 208},
		{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
		{26: 210, 30: 211},
		{25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25},
		// 80
		{24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24},
		{26: 213},
		{26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26},
		{27: 215},
		{21: 216},
		// 85
		{26: 217},
		{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
		{91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91},
		{90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90},
		{214, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89},
		// 90
		{223, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 48: 227},
		{84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84},
		{29: 224},
		{21: 225},
		{28: 226},
		// 95
		{37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37},
		{85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85},
		{203, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 22: 234, 33: 233, 35: 232},
		{80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80},
		{79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79},
		// 100
		{214, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78},
		{83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83},
		{82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82},
		{214, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81},
		{238, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 22: 244, 51: 245},
		// 105
		{214, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75},
		{74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74},
		{27: 206, 52: 239},
		{21: 240},
		{39: 243, 41: 242, 54: 241},
		// 110
		{9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
		{8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8},
		{7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
		{214, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77},
		{76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76},
		// 115
		{251, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 256, 22: 257, 255, 49: 258},
		{69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69},
		{68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68},
		{214, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67},
		{66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66},
		// 120
		{25: 157, 27: 206, 29: 158, 80: 252},
		{21: 253},
		{28: 167, 36: 166, 38: 254},
		{34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34},
		{73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73},
		// 125
		{72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72},
		{214, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71},
		{70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70},
		{214, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120},
		{27: 206},
		// 130
		{156, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 264, 23: 265},
		{63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63},
		{62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62},
		{65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65},
		{64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64},
		// 135
		{275, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 303, 23: 307, 301, 31: 305, 34: 302, 45: 308, 306, 50: 304},
		{53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53},
		{52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52},
		{51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51},
		{50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50},
		// 140
		{49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49},
		{48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48},
		{47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47},
		{46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46},
		{25: 157, 29: 158, 37: 187, 40: 278, 52: 277, 276, 55: 280, 58: 279},
		// 145
		{21: 297},
		{21: 292},
		{21: 287},
		{21: 285},
		{21: 281},
		// 150
		{283, 30: 282},
		{6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6},
		{30: 284},
		{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5},
		{39: 243, 41: 242, 54: 286},
		// 155
		{10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10},
		{57: 289, 60: 290, 82: 288, 86: 291},
		{15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15},
		{13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13},
		{12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12},
		// 160
		{11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11},
		{44: 294, 59: 295, 64: 296, 84: 293},
		{19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19},
		{18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18},
		{17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17},
		// 165
		{16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16},
		{63: 299, 78: 300, 85: 298},
		{22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22},
		{21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21},
		{20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20},
		// 170
		{61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61},
		{60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60},
		{59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59},
		{58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58},
		{57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57},
		// 175
		{56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56},
		{55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55},
		{54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54},
		{1: 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123},
		{315, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 317, 24: 316, 31: 319, 34: 318},
		// 180
		{41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41},
		{40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40},
		{39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39},
		{38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38},
		{25: 157, 37: 187, 40: 278, 53: 276},
		// 185
		{45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45},
		{44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44},
		{43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43},
		{42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42},
		{1: 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125},
		// 190
		{1: 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 95

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			AddAST()
		}
	case 4:
		{
			AddInstruccion("pause")
		}
	case 5:
		{
			AddInstruccion("logout")
		}
	case 6:
		{
			EjecutarExec()
		}
	case 7:
		{
			AddInstruccion("mkdisk")
		}
	case 8:
		{
			AddParametro()
			AddInstruccion("rmdisk")
		}
	case 9:
		{
			AddInstruccion("fdisk")
		}
	case 10:
		{
			AddInstruccion("mount")
		}
	case 11:
		{
			AddParametro()
			AddInstruccion("unmount")
		}
	case 12:
		{
			AddInstruccion("rep")
		}
	case 13:
		{
			AddInstruccion("mkfs")
		}
	case 14:
		{
			AddInstruccion("login")
		}
	case 15:
		{
			AddInstruccion("mkgrp")
		}
	case 16:
		{
			AddInstruccion("mkusr")
		}
	case 17:
		{
			AddInstruccion("mkfile")
		}
	case 18:
		{
			AddInstruccion("mkdir")
		}
	case 19:
		{
			AddInstruccion("rem")
		}
	case 20:
		{
			AddInstruccion("cat")
		}
	case 21:
		{
			AddInstruccion("ren")
		}
	case 22:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 23:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 24:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 25:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 26:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 27:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 28:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 29:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 30:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 31:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 32:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 33:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 34:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 35:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 36:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 37:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 38:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 39:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 40:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 41:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 42:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 43:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 44:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 45:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 46:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 47:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 48:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 49:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 50:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 51:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 52:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 53:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 54:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 55:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 56:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 57:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 58:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 59:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 60:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 61:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 62:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 63:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 64:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 65:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 66:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 67:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 68:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 69:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 70:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 71:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 72:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 73:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 74:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 75:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 76:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 77:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			AddParametro()
		}
	case 78:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 79:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 80:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 81:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 82:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 83:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 84:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 85:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 86:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 87:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 88:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 89:
		{
			yyVAL.value = yyS[yypt-1].value
			AddParametro()
		}
	case 90:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 91:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 92:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 93:
		{
			yyVAL.value = yyS[yypt-0].value
			AddParametro()
		}
	case 94:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 95:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 96:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			auxPath = yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 97:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			auxPath = yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 98:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 99:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 100:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 101:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 102:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 103:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 104:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 105:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 106:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 107:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 108:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 109:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 110:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 111:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 112:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 113:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 114:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 115:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 116:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 117:
		{
			yyVAL.value = yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-0].value, yyS[yypt-0].value)
		}
	case 118:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 119:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 120:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 121:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 122:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 123:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 124:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 125:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 126:
		{
			yyVAL.value = yyS[yypt-4].value + yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-3].value, "-"+yyS[yypt-0].value)
		}
	case 127:
		{
			yyVAL.value = yyS[yypt-4].value + yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
		}
	case 128:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
		}
	case 129:
		{
			yyVAL.value = yyS[yypt-4].value + yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}
	case 130:
		{
			yyVAL.value = yyS[yypt-3].value + yyS[yypt-2].value + yyS[yypt-1].value + yyS[yypt-0].value
			CrearParametro(yyS[yypt-2].value, yyS[yypt-0].value)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}

// CrearParametro da un valor nuevo al parámetro axuliar
func CrearParametro(tipo string, valor string) {
	oParametro = arbol.Parametro{Tipo: tipo, Valor: valor}
}

// CrearInstruccion da un valor nuevo a la intruccion auxiliar
func CrearInstruccion(tipo string) {
	oInstruccion = arbol.Instruccion{Tipo: tipo}
}

// AddParametro añade el parámetro auxiliar a la lista de parametros de la instrucción actual
func AddParametro() {
	oInstruccion.Parametros = append(oInstruccion.Parametros, oParametro)
}

// AddInstruccion añade el parámetro auxiliar a la lista de parametros de la instrucción actual
func AddInstruccion(tipo string) {
	oInstruccion.Tipo = tipo
	lInstruccion = append(lInstruccion, oInstruccion)
	oInstruccion = arbol.Instruccion{}
}

// AddAST añade lista de instrucciones para ejecutar
func AddAST() {
	ast := arbol.AST{}
	ast.Instrucciones = lInstruccion
	lInstruccion = []arbol.Instruccion{}
	lAST = append(lAST, ast)
}

func EjecutarExec() {
	if file, err := os.Open(auxPath); err == nil {
		yyParse(newLexer(bufio.NewReader(file)))

		ast := lAST[len(lAST)-1]
		ast.EjecutarAST()
		lAST = lAST[:len(lAST)-1]

		fmt.Println("Se ha ejecutado el archivo con èxito")
	} else {
		fmt.Println("No se ha podido abrir el archivo")
		log.Panic(err)
	}
}
